# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97c2366dc1c2b0d4f24c8df851ade4a041461478aa6fff522cc8a4e18ad25414261c4a64cf16fa31cfb0f12a857583888657aac17caee0eaeaed7d4ef040166b

test:
  secret_key_base: 3f9bec3c802267a5b0499f7f5594cad2c975c70d8c2326a2cbfef0d92f5c5c6e6e96f3dbac1e18c40c7f48467dc2a838a84f512eb258f3f103e19a24aaa063a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
